criaCartao('Programação', 'O que é Python?', 'Uma linguagem de programação simples e poderosa.')
criaCartao('Geografia', 'Capital da França?', 'Paris.')
criaCartao('Matemática', 'Quanto é 2 + 2?', '4.')
criaCartao('História', 'Quem descobriu o Brasil?', 'Pedro Álvares Cabral.')
criaCartao('Inglês', 'Como dizemos "olá"?', 'Hello.')
criaCartao('Ciências', 'Planeta mais próximo do Sol?', 'Mercúrio.')
criaCartao('Artes', 'Quem pintou a Mona Lisa?', 'Leonardo da Vinci.')
criaCartao('Português', 'Plural de "pão"?', 'Pães.')
criaCartao('Biologia', 'O que é fotossíntese?', 'Processo em que plantas produzem alimento.')
criaCartao('Química', 'Símbolo do Ouro?', 'Au.')
criaCartao('Física', 'Força que nos prende ao chão?', 'Gravidade.')
criaCartao('Tecnologia', 'O que é HTML?', 'Linguagem de marcação para web.')